export const FETCH_COUNTERS = 'FETCH_COUNTERS';
export const CREATE_COUNTER = 'CREATE_COUNTER';
export const REMOVE_COUNTER = 'REMOVE_COUNTER';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const FETCH_COUNTERS_SUCCESS = 'FETCH_COUNTERS_SUCCESS';
export const CREATE_COUNTER_SUCCESS = 'CREATE_COUNTER_SUCCESS';
export const REMOVE_COUNTER_SUCCESS = 'REMOVE_COUNTER_SUCCESS';
export const INCREMENT_COUNTER_SUCCESS = 'INCREMENT_COUNTER_SUCCESS';
export const DECREMENT_COUNTER_SUCCESS = 'DECREMENT_COUNTER_SUCCESS';

export const API_ERROR = 'API_ERROR';
export const UPDATE_STATE = 'UPDATE_STATE';
